name: Cypress CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install and Run Tests
        uses: cypress-io/github-action@v6
        with:
  
          install-command: npm ci

          command: npm test